"""
Physics-driven fracture trigger.

Decides WHEN and WHERE a fracture event should start, using the MPM-projected
physics field. Also returns the WHERE's local stress frame (principal tensile
direction) which the pattern synthesizer uses as the initial crack orientation.

This module does NOT evolve cracks on its own — it only identifies the
nucleation event. A separate pattern synthesizer turns the nucleation into a
procedural crack skeleton.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import torch
from torch import Tensor


@dataclass
class FractureTrigger:
    """A single fracture nucleation event detected by the physics trigger."""
    nucleation_idx: int            # Index of the Gaussian where fracture initiates
    nucleation_pos: Tensor         # (3,) world-space position
    principal_dir: Tensor          # (3,) unit vector — local σ₁ direction (crack normal)
    stress_magnitude: float        # σ₁ magnitude at nucleation, for pattern sizing
    trigger_frame: int             # Frame index when this trigger fired
    is_impact: bool = False        # True if fired from ground impact, False from σ threshold


class PhysicsTrigger:
    """Detects fracture nucleation events from the projected physics field.

    Two trigger paths:
      1. IMPACT mode — fires once at ground-contact frame (strongest signal).
         Uses contact position as nucleation; principal direction from the
         stress tensor at the nearest Gaussian.
      2. STRESS mode — fires when σ_max surpasses a threshold anywhere
         on the surface. Useful for non-impact loading (seismic, pull, etc.).

    Usage:
        trig = PhysicsTrigger(stress_threshold=1e5)
        event = trig.check_impact(contact_pos, stress_field, positions, frame)
        # or
        event = trig.check_stress_threshold(stress_field, positions, frame)
        if event:
            pattern = synthesizer.generate(event, ...)
    """

    def __init__(
        self,
        stress_threshold: float = 1e5,
        cooldown_frames: int = 5,
    ):
        """
        Args:
            stress_threshold: σ_max above which STRESS mode triggers
                              (ignored if IMPACT mode already fired).
            cooldown_frames: minimum frames between consecutive triggers.
        """
        self.stress_threshold = float(stress_threshold)
        self.cooldown_frames = int(cooldown_frames)
        self._last_trigger_frame: int = -10_000
        self._has_impact_fired: bool = False

    def reset(self) -> None:
        """Clear trigger state (call between independent runs)."""
        self._last_trigger_frame = -10_000
        self._has_impact_fired = False

    @torch.no_grad()
    def check_impact(
        self,
        contact_pos: Tensor,
        stress_field: Optional[Tensor],
        positions: Tensor,
        frame: int,
        neighborhood_radius: float = 0.15,
    ) -> Optional[FractureTrigger]:
        """Fire a one-shot trigger at ground impact.

        Nucleation site is the Gaussian nearest to the impact. Principal
        direction σ₁, however, is extracted from the GLOBAL tensile hotspot
        (max σ₁ over all nodes) instead of the nucleation cell itself —
        because the contact zone is in compression (σ₁ ≤ 0 there), while
        meaningful tensile stress develops on the sides/rebound regions.
        This gives the synthesizer a real physics direction that is not
        degenerated by the compressive contact.
        """
        if self._has_impact_fired:
            return None

        # Find the Gaussian nearest to contact.
        dists = (positions - contact_pos.unsqueeze(0)).norm(dim=1)
        nuc_idx = int(dists.argmin().item())
        nuc_pos = positions[nuc_idx]

        # Principal tensile direction from the GLOBAL tensile peak.
        principal_dir, sigma1 = self._global_principal_tensile(stress_field)
        if principal_dir is None:
            # Last resort fallback: use local σ₁ at the nucleation.
            principal_dir, sigma1 = self._local_principal_tensile(
                stress_field, nuc_idx
            )
        if principal_dir is None:
            # No tensile stress yet — defer by not triggering.
            return None

        self._has_impact_fired = True
        self._last_trigger_frame = frame
        return FractureTrigger(
            nucleation_idx=nuc_idx,
            nucleation_pos=nuc_pos.detach().clone(),
            principal_dir=principal_dir.detach().clone(),
            stress_magnitude=float(sigma1),
            trigger_frame=frame,
            is_impact=True,
        )

    @torch.no_grad()
    def check_stress_threshold(
        self,
        stress_field: Tensor,
        positions: Tensor,
        frame: int,
    ) -> Optional[FractureTrigger]:
        """Fire a trigger when the largest principal tensile stress crosses
        the configured threshold. Respects cooldown.
        """
        if (frame - self._last_trigger_frame) < self.cooldown_frames:
            return None

        if stress_field is None or stress_field.shape[0] == 0:
            return None

        # Per-node σ₁ (largest eigenvalue, positive = tension).
        S = 0.5 * (stress_field + stress_field.transpose(1, 2))
        try:
            eigenvalues, _ = torch.linalg.eigh(S)
        except Exception:
            return None
        sigma1_per_node = eigenvalues[:, -1].clamp(min=0.0)  # (N,)
        s_max = float(sigma1_per_node.max().item())
        if s_max < self.stress_threshold:
            return None

        nuc_idx = int(sigma1_per_node.argmax().item())
        nuc_pos = positions[nuc_idx]
        principal_dir, _ = self._local_principal_tensile(stress_field, nuc_idx)
        if principal_dir is None:
            principal_dir = torch.tensor(
                [0.0, 0.0, 1.0], device=positions.device, dtype=positions.dtype
            )

        self._last_trigger_frame = frame
        return FractureTrigger(
            nucleation_idx=nuc_idx,
            nucleation_pos=nuc_pos.detach().clone(),
            principal_dir=principal_dir.detach().clone(),
            stress_magnitude=s_max,
            trigger_frame=frame,
            is_impact=False,
        )

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    @staticmethod
    @torch.no_grad()
    def _local_principal_tensile(
        stress_field: Optional[Tensor],
        idx: int,
    ) -> Tuple[Optional[Tensor], float]:
        """Return (unit principal tensile direction, σ₁ magnitude) at idx."""
        if stress_field is None:
            return None, 0.0
        S = stress_field[idx]
        S_sym = 0.5 * (S + S.t())
        try:
            eig, vec = torch.linalg.eigh(S_sym)
        except Exception:
            return None, 0.0
        sigma1 = float(eig[-1].item())
        if sigma1 <= 0.0:
            return None, 0.0
        direction = vec[:, -1]
        norm = direction.norm().clamp(min=1e-8)
        return (direction / norm), sigma1

    @staticmethod
    @torch.no_grad()
    def _global_principal_tensile(
        stress_field: Optional[Tensor],
    ) -> Tuple[Optional[Tensor], float]:
        """Return (unit σ₁ direction, σ₁ magnitude) from the GLOBAL tensile peak.

        Finds the node with the largest positive σ₁, returns that node's
        principal tensile eigenvector. Used as the trigger's reference
        direction when the contact zone itself is compressive.
        """
        if stress_field is None or stress_field.shape[0] == 0:
            return None, 0.0
        S = 0.5 * (stress_field + stress_field.transpose(1, 2))
        try:
            eigenvalues, eigenvectors = torch.linalg.eigh(S)
        except Exception:
            return None, 0.0
        sigma1_per_node = eigenvalues[:, -1]  # (N,) — can be negative
        s_max = float(sigma1_per_node.max().item())
        if s_max <= 0.0:
            return None, 0.0
        peak_idx = int(sigma1_per_node.argmax().item())
        direction = eigenvectors[peak_idx, :, -1]
        norm = direction.norm().clamp(min=1e-8)
        return (direction / norm), s_max
